### ISSUE TITLE
Error on finishing simplecov run, no coverage output

### ISSUE THREAD

**Issue by ragesoss** [deep-cover/deep-cover#12]
I just ran my Rails test suite ([for this app](https://github.com/WikiEducationFoundation/WikiEduDashboard)) with deep-cover. At the end, it throws an error and does not report any details of coverage:

```
Finished in 13 minutes 4 seconds (files took 13 minutes 15 seconds to load)
1166 examples, 0 failures, 12 pending

/home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/exceptions.rb:55:in `resbodies_flow_entry_count': undefined method `flow_completion_count' for nil:NilClass (NoMethodError)
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/mixin/has_child_handler.rb:17:in `call_child_handler'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/mixin/has_child_handler.rb:39:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/mixin/flow_accounting.rb:20:in `flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/mixin/flow_accounting.rb:58:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/mixin/has_child_handler.rb:40:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/mixin/flow_accounting.rb:20:in `flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/node/mixin/flow_accounting.rb:38:in `execution_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/covered_code_source.rb:16:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:17:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/ignore_uncovered.rb:12:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:17:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/ignore_uncovered.rb:12:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/per_line.rb:8:in `block in results'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:36:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/analyser/per_line.rb:7:in `results'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/covered_code.rb:51:in `line_coverage'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/core_ext/coverage_replacement.rb:22:in `block in peek'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/core_ext/coverage_replacement.rb:21:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/core_ext/coverage_replacement.rb:21:in `map'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/core_ext/coverage_replacement.rb:21:in `peek'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-2857a0c83031/lib/deep_cover/core_ext/coverage_replacement.rb:17:in `result'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov.rb:82:in `result'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov/configuration.rb:180:in `block in at_exit'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov/defaults.rb:68:in `block in <top (required)>'
/home/sage/.rbenv/versions/2.3.1/bin/ruby -I/home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.0/lib:/home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.0/lib /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.0/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

**Comment by MaxLap** [comment]
Released v0.1.12 which should solve this issue.

Thank you for the report.

I'm working on adding some diagnostic output for errors such as this one.
