### ISSUE TITLE
Reporting crashes for unparsable files

### ISSUE THREAD

**Issue by marcandre** [deep-cover/deep-cover#26]
e.g. AR:

```
1 files could not be instrumented because of syntax errors:
activesupport/activesupport/lib/active_support/core_ext/digest/uuid.rb
```

**Comment by marcandre** [comment]
```
	29: from /Users/mal/deep-cover/lib/deep_cover/reporter/html/index.rb:13:in `stats_to_data'
	28: from /Users/mal/deep-cover/lib/deep_cover/reporter/base.rb:35:in `populate_stats'
	27: from /Users/mal/deep-cover/lib/deep_cover/memoize.rb:41:in `tree'
	26: from /Users/mal/deep-cover/lib/deep_cover/reporter/base.rb:64:in `tree'
	25: from /Users/mal/deep-cover/lib/deep_cover/memoize.rb:41:in `map'
	24: from /Users/mal/deep-cover/lib/deep_cover/reporter/base.rb:60:in `map'
	23: from /Users/mal/deep-cover/lib/deep_cover/memoize.rb:41:in `analysis'
	22: from /Users/mal/deep-cover/lib/deep_cover/reporter/base.rb:19:in `analysis'
	21: from /Users/mal/deep-cover/lib/deep_cover/coverage.rb:21:in `covered_codes'
	20: from /Users/mal/deep-cover/lib/deep_cover/coverage.rb:21:in `to_a'
	19: from /Users/mal/deep-cover/lib/deep_cover/coverage.rb:21:in `each'
	18: from /Users/mal/deep-cover/lib/deep_cover/coverage.rb:38:in `each'
	17: from /Users/mal/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/forwardable.rb:229:in `each_key'
	16: from /Users/mal/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/forwardable.rb:229:in `each_key'
	15: from /Users/mal/deep-cover/lib/deep_cover/coverage.rb:38:in `block in each'
	14: from /Users/mal/deep-cover/lib/deep_cover/coverage.rb:30:in `covered_code'
	13: from /Users/mal/deep-cover/lib/deep_cover/coverage.rb:30:in `new'
	12: from /Users/mal/deep-cover/lib/deep_cover/covered_code.rb:26:in `initialize'
	11: from /Users/mal/deep-cover/lib/deep_cover/covered_code.rb:85:in `instrument_source'
	10: from /Users/mal/deep-cover/lib/deep_cover/covered_code.rb:64:in `covered_ast'
	 9: from /Users/mal/deep-cover/lib/deep_cover/covered_code.rb:74:in `root'
	 8: from /Users/mal/.rvm/gems/ruby-2.5.0/gems/parser-2.5.1.0/lib/parser/base.rb:184:in `parse_with_comments'
	 7: from /Users/mal/.rvm/gems/ruby-2.5.0/gems/parser-2.5.1.0/lib/parser/base.rb:167:in `parse'
	 6: from /Users/mal/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/racc/parser.rb:259:in `do_parse'
	 5: from /Users/mal/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/racc/parser.rb:259:in `_racc_do_parse_c'
	 4: from /Users/mal/.rvm/gems/ruby-2.5.0/gems/parser-2.5.1.0/lib/parser/ruby25.rb:5736:in `_reduce_443'
	 3: from /Users/mal/.rvm/gems/ruby-2.5.0/gems/parser-2.5.1.0/lib/parser/builders/default.rb:193:in `string'
	 2: from /Users/mal/.rvm/gems/ruby-2.5.0/gems/parser-2.5.1.0/lib/parser/builders/default.rb:1646:in `string_value'
	 1: from /Users/mal/.rvm/gems/ruby-2.5.0/gems/parser-2.5.1.0/lib/parser/builders/default.rb:1658:in `diagnostic'
/Users/mal/.rvm/gems/ruby-2.5.0/gems/parser-2.5.1.0/lib/parser/diagnostic/engine.rb:73:in `process': literal contains escape sequences incompatible with UTF-8 (Parser::SyntaxError)
```

**Comment by MaxLap** [comment]
I'd be tempted to look into fixing this parser issue...

For now, I made unparsable files be ignored from the reporting.

**Comment by marcandre** [comment]
> I'd be tempted to look into fixing this parser issue...

Don't: https://github.com/whitequark/parser#invalid-characters-inside-comments-and-literals
