### ISSUE TITLE
Path related failures on OS X

### ISSUE THREAD

**Issue by marcandre** [deep-cover/deep-cover#34]
I've been getting these for a while now. Any chance you might have a look at them @MaxLap ?

```
Failures:

  1) DeepCover::CustomRequirer#require indicates that .so files are not supported when the .so is specified and the file is found
     Failure/Error: 'two/test.so'.should actually_require(:file_extension_is_so)
     
       Unexpected effects of `require "two/test.so"`:
       Return value:
         expected: :file_extension_is_so
         ruby:     :not_found
         custom:   :file_extension_is_so
     
       Executed file:
         expected: nil
         ruby:     nil
         custom:   nil
     
       Loaded features:
         expected: []
         ruby:     []
         custom:   []
     # ./spec/custom_requirer_spec.rb:573:in `block (3 levels) in <module:DeepCover>'
     # ./spec/custom_requirer_spec.rb:17:in `block (2 levels) in <module:DeepCover>'

  2) DeepCover::CustomRequirer#require indicates that .so files are not supported when the .so is not specified and the file is found
     Failure/Error: 'two/test'.should actually_require(:file_extension_is_so)
     
       Unexpected effects of `require "two/test"`:
       Return value:
         expected: :file_extension_is_so
         ruby:     :not_found
         custom:   :file_extension_is_so
     
       Executed file:
         expected: nil
         ruby:     nil
         custom:   nil
     
       Loaded features:
         expected: []
         ruby:     []
         custom:   []
     # ./spec/custom_requirer_spec.rb:580:in `block (3 levels) in <module:DeepCover>'
     # ./spec/custom_requirer_spec.rb:17:in `block (2 levels) in <module:DeepCover>'

  3) DeepCover::CustomRequirer#require prefers .rb files over .so files if in same LOAD_PATH
     Failure/Error: 'two/test.so'.should actually_require(:file_extension_is_so)
     
       Unexpected effects of `require "two/test.so"`:
       Return value:
         expected: :file_extension_is_so
         ruby:     :not_found
         custom:   :file_extension_is_so
     
       Executed file:
         expected: nil
         ruby:     nil
         custom:   nil
     
       Loaded features:
         expected: ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-15hv156/one/two/test.rb"]
         ruby:     ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-15hv156/one/two/test.rb"]
         custom:   ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-15hv156/one/two/test.rb"]
     # ./spec/custom_requirer_spec.rb:596:in `block (3 levels) in <module:DeepCover>'
     # ./spec/custom_requirer_spec.rb:17:in `block (2 levels) in <module:DeepCover>'

  4) DeepCover::CustomRequirer#require prefers .rb files of a later LOAD_PATH over previous .so files
     Failure/Error: 'two/test.so'.should actually_require(:file_extension_is_so)
     
       Unexpected effects of `require "two/test.so"`:
       Return value:
         expected: :file_extension_is_so
         ruby:     :not_found
         custom:   :file_extension_is_so
     
       Executed file:
         expected: nil
         ruby:     nil
         custom:   nil
     
       Loaded features:
         expected: ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-1eydpys/then/two/test.rb"]
         ruby:     ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-1eydpys/then/two/test.rb"]
         custom:   ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-1eydpys/then/two/test.rb"]
     # ./spec/custom_requirer_spec.rb:609:in `block (3 levels) in <module:DeepCover>'
     # ./spec/custom_requirer_spec.rb:17:in `block (2 levels) in <module:DeepCover>'

  5) DeepCover::CustomRequirer#require prefers .rb files of a previous LOAD_PATH over .so file that follows
     Failure/Error: 'two/test.so'.should actually_require(:file_extension_is_so)
     
       Unexpected effects of `require "two/test.so"`:
       Return value:
         expected: :file_extension_is_so
         ruby:     :not_found
         custom:   :file_extension_is_so
     
       Executed file:
         expected: nil
         ruby:     nil
         custom:   nil
     
       Loaded features:
         expected: ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-4m3fvb/one/two/test.rb"]
         ruby:     ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-4m3fvb/one/two/test.rb"]
         custom:   ["/private/var/folders/8j/wl5k_jn571b3_lt3hxskxz540000gp/T/deep_cover_test20180706-35494-4m3fvb/one/two/test.rb"]
     # ./spec/custom_requirer_spec.rb:621:in `block (3 levels) in <module:DeepCover>'
     # ./spec/custom_requirer_spec.rb:17:in `block (2 levels) in <module:DeepCover>'

Finished in 11.28 seconds (files took 1.54 seconds to load)
911 examples, 5 failures, 1 pending

Failed examples:

rspec ./spec/custom_requirer_spec.rb:569 # DeepCover::CustomRequirer#require indicates that .so files are not supported when the .so is specified and the file is found
rspec ./spec/custom_requirer_spec.rb:576 # DeepCover::CustomRequirer#require indicates that .so files are not supported when the .so is not specified and the file is found
rspec ./spec/custom_requirer_spec.rb:588 # DeepCover::CustomRequirer#require prefers .rb files over .so files if in same LOAD_PATH
rspec ./spec/custom_requirer_spec.rb:599 # DeepCover::CustomRequirer#require prefers .rb files of a later LOAD_PATH over previous .so files
rspec ./spec/custom_requirer_spec.rb:612 # DeepCover::CustomRequirer#require prefers .rb files of a previous LOAD_PATH over .so file that follows
```

**Comment by MaxLap** [comment]
Gj
