### ISSUE TITLE
run-expression

### ISSUE THREAD

**Issue by marcandre** [deep-cover/deep-cover#49]
Oops

```
[12:07][~]$ gem install deep-cover
Fetching deep-cover-0.7.1.gem
Fetching deep-cover-core-0.7.1.gem
Successfully installed deep-cover-core-0.7.1
Successfully installed deep-cover-0.7.1
2 gems installed
[12:08][~]$ deep-cover run-expression ":hello"
Traceback (most recent call last):
	11: from /Users/mal/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `<main>'
	10: from /Users/mal/.rvm/gems/ruby-2.6.2/bin/ruby_executable_hooks:24:in `eval'
	 9: from /Users/mal/.rvm/gems/ruby-2.6.2/bin/deep-cover:23:in `<main>'
	 8: from /Users/mal/.rvm/gems/ruby-2.6.2/bin/deep-cover:23:in `load'
	 7: from /Users/mal/.rvm/gems/ruby-2.6.2/gems/deep-cover-0.7.1/exe/deep-cover:12:in `<top (required)>'
	 6: from /Users/mal/.rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	 5: from /Users/mal/.rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	 4: from /Users/mal/.rvm/gems/ruby-2.6.2/gems/deep-cover-0.7.1/lib/deep_cover/cli.rb:81:in `invoke_command'
	 3: from /Users/mal/.rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	 2: from /Users/mal/.rvm/gems/ruby-2.6.2/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	 1: from /Users/mal/.rvm/gems/ruby-2.6.2/gems/deep-cover-0.7.1/lib/deep_cover/cli/commands/run_expression.rb:9:in `run_expression'
/Users/mal/.rvm/gems/ruby-2.6.2/gems/deep-cover-0.7.1/lib/deep_cover/cli/commands/run_expression.rb:9:in `require_relative': cannot load such file -- /Users/mal/.rvm/gems/ruby-2.6.2/gems/deep-cover-0.7.1/lib/deep_cover/cli/expression_debugger (LoadError)
[12:08][~]$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
```

**Comment by MaxLap** [comment]
Fixed by marcandre in 32ac4059ce7ffe6e492191712a3ab305d913528a
