### ISSUE TITLE
Errors with loading some gems is spec helper

### ISSUE THREAD

**Issue by ragesoss** [deep-cover/deep-cover#6]
I get errors when trying this out on my rails test suite.

First:
```
Failure/Error: require 'webmock/rspec'

Parser::SyntaxError:
  literal contains escape sequences incompatible with UTF-8
```

After commenting that out:
```
Failure/Error: require 'sidekiq/testing'

SyntaxError:
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:61: syntax error, unexpected '|', expecting '}'
  ...{$_cov[131][49]+=1;_temp=nil; |*_| });$_cov[131][48]+=1;_tem...
  ...                               ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:61: syntax error, unexpected ')', expecting '}'
  ...;$_cov[131][48]+=1;_temp=_temp)));$_cov[131][50]+=1;_temp=_t...
  ...                               ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:61: syntax error, unexpected ')', expecting '}'
  ...;$_cov[131][50]+=1;_temp=_temp))
  ...                               ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:62: syntax error, unexpected ')', expecting '}'
        end);$_cov[131][51]+=1;_temp=_temp))
                                           ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:65: syntax error, unexpected keyword_end, expecting '}'
      end);$_cov[131][53]+=1;_temp=_temp))
         ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:65: syntax error, unexpected ')', expecting '}'
      end);$_cov[131][53]+=1;_temp=_temp))
                                         ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:90: syntax error, unexpected keyword_end, expecting '}'
    end);$_cov[131][73]+=1;_temp=_temp))
       ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:90: syntax error, unexpected ')', expecting '}'
    end);$_cov[131][73]+=1;_temp=_temp))
                                       ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/redis-4.0.1/lib/redis/subscribe.rb:91: syntax error, unexpected ')', expecting '}'
  end);$_cov[131][75]+=1;_temp=_temp))
                                     ^
```

After moving the coverage bits including deep-cover to the end of spec_helper, the tests all fail with mostly NameError and NoMethodError:

```
An error occurred while loading ./spec/models/campaigns_users_spec.rb.
Failure/Error:
  describe CampaignsUsers, type: :model do
  end

NameError:
  uninitialized constant CampaignsUsers
# ./spec/models/campaigns_users_spec.rb:17:in `<top (required)>'
```

**Comment by marcandre** [comment]
Thanks for the report!

1) The utf thing is strange. I'm having other issues so can't quite investigate yet

2) This is very helpful, a case of Ruby code we're choking on. I can reproduce it on my end so I hope to fix it tomorrow.

3) This is also interesting, looks like we might be introducing an issue with Rails autoloading of modules. I've opened #8 for this.

**Comment by marcandre** [comment]
1) Ok, figured out the source, created #9.

2) Fixed & released.

To circumvent #3, you can try calling `Rails.application.eager_load!`, but that will probably fail too because of loading order issues.

**Comment by ragesoss** [comment]
After the fixes, I end up dumped into Pry before any tests run:

```
From: /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-691e2a084f2b/lib/deep_cover/node/mixin/has_child.rb @ line 12 DeepCover::Node::Mixin::HasChild#initialize:

    10: def initialize(*)
    11:   super
 => 12:   self.validate_children_types(children) rescue binding.pry
    13: end

[1] pry(#<DeepCover::Node::Casgn>)> 
```

**Comment by marcandre** [comment]
Oh, cool (for us ;-) ), means we don't support some of your code. Let me remove this debugging code and make sure some meaningful diagnostic appear...

**Comment by marcandre** [comment]
Thanks again for your feedback. I pushed a new version that will hopefully output the source code that we are not processing correctly.

**Comment by ragesoss** [comment]
Now the specs are running again (after a few minutes of delay), and this error is at the beginning:

```
Node class DeepCover::Node::Casgn incorrectly defined
Attempting to continue, but this node will not be handled properly

Source:
self::OrmAdapter = ::OrmAdapter::ActiveRecord
Original exception:
#<TypeError: Invalid children types for DeepCover::Node::Casgn(type: casgn): [[(self[Node]), [DeepCover::Node::Cbase, DeepCover::Node::Const, nil]]]>
```

Then...
```
An error occurred while loading ./spec/controllers/admin_controller_spec.rb.
Failure/Error: require File.expand_path('../../config/environment', __FILE__)

SyntaxError:
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.3.0/lib/devise/rails.rb:24: syntax error, unexpected keyword_do, expecting ')'
  ...cov[957][33]+=1;_temp=_temp) do |strategy|
  ...                               ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.3.0/lib/devise/rails.rb:26: syntax error, unexpected keyword_end, expecting ')'
          end);$_cov[957][35]+=1;_temp=_temp))
             ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.3.0/lib/devise/rails.rb:27: syntax error, unexpected keyword_end, expecting ')'
        end);$_cov[957][37]+=1;_temp=_temp))
           ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.3.0/lib/devise/rails.rb:27: syntax error, unexpected ')', expecting keyword_end
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/devise-4.3.0/lib/devise/rails.rb:49: syntax error, unexpected end-of-input, expecting keyword_end
# ./config/application.rb:7:in `<top (required)>'
# ./config/environment.rb:2:in `<top (required)>'
# ./spec/rails_helper.rb:7:in `<top (required)>'
# ./spec/controllers/admin_controller_spec.rb:3:in `require'
# ./spec/controllers/admin_controller_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/controllers/alerts_controller_spec.rb.
Failure/Error: require 'rspec/rails'

SyntaxError:
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.7.1/lib/rspec/rails/matchers/routing_matchers.rb:25: syntax error, unexpected keyword_do, expecting ')'
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.7.1/lib/rspec/rails/matchers/routing_matchers.rb:32: syntax error, unexpected keyword_end, expecting ')'
              end);$_cov[994][38]+=1;_temp=_temp))
                 ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.7.1/lib/rspec/rails/matchers/routing_matchers.rb:33: syntax error, unexpected keyword_end, expecting ')'
            end);$_cov[994][40]+=1;_temp=_temp))
               ^
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.7.1/lib/rspec/rails/matchers/routing_matchers.rb:33: syntax error, unexpected ')', expecting keyword_end
  /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.7.1/lib/rspec/rails/matchers/routing_matchers.rb:125: syntax error, unexpected end-of-input, expecting keyword_end
# ./spec/rails_helper.rb:8:in `<top (required)>'
# ./spec/controllers/alerts_controller_spec.rb:3:in `<top (required)>'
```

The autoloading issues are also there; haven't tried eager loading yet as you suggested above.

**Comment by ragesoss** [comment]
Also at the end:

```
/home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/exceptions.rb:55:in `resbodies_flow_entry_count': undefined method `flow_completion_count' for nil:NilClass (NoMethodError)
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/mixin/has_child_handler.rb:17:in `call_child_handler'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/mixin/has_child_handler.rb:39:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/mixin/flow_accounting.rb:20:in `flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/mixin/flow_accounting.rb:58:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/mixin/has_child_handler.rb:40:in `child_flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/mixin/flow_accounting.rb:20:in `flow_entry_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/node/mixin/flow_accounting.rb:38:in `execution_count'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/covered_code_source.rb:16:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:17:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/ignore_uncovered.rb:12:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:17:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/ignore_uncovered.rb:12:in `node_runs'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/per_line.rb:8:in `block in results'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:36:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:38:in `block in each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/base.rb:37:in `each_node'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/analyser/per_line.rb:7:in `results'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/covered_code.rb:55:in `line_coverage'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/core_ext/coverage_replacement.rb:22:in `block in peek'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/core_ext/coverage_replacement.rb:21:in `each'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/core_ext/coverage_replacement.rb:21:in `map'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/core_ext/coverage_replacement.rb:21:in `peek'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/deep-cover-bdea8e6fa30e/lib/deep_cover/core_ext/coverage_replacement.rb:17:in `result'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov.rb:82:in `result'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov/configuration.rb:180:in `block in at_exit'
	from /home/sage/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/simplecov-0.15.1/lib/simplecov/defaults.rb:68:in `block in <top (required)>'
```

**Comment by marcandre** [comment]
Nice, thanks for the bug reports :+1: (and sorry for them, but hey, we're early in the pre-releases 😈 ).
* `self::OrmAdapter = ::OrmAdapter::ActiveRecord` => Fixed & released
* error loading devise => Fixed & released
* after that, it doesn't look like it's because of the previous error, but maybe... I probably should add some diagnostics in case it happen though.

**Comment by ragesoss** [comment]
I'm still stuck on the `NameError` issue. I tried `Rails.application.eager_load!` in the spec_helper, but that gives `NameError: uninitialized constant Rails`. I'll try again after #8 closes.

**Comment by MaxLap** [comment]
I think everything from this has been fixed, right? New problems should be in new issues.
